### ISSUE TITLE
making nested properties reactive?

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/Discussion#208]
I have an object in a model.  I need for nested property changes in that object to trigger reactions.  If I use a $set on a nested property I get this...

```
[Vue warn]: You are setting a non-existent path "curShow.tags.MarkOnly" on a vm instance. 
Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.
```

To fix this I am putting each nesting level directly in the data section like this ...

```
  data:
    allShows: {}
    curShow: {}
    curTags:  {}

  watched:
    curShowIdx: (idx) -> 
        @curShow = show = @allShows[idx]
        @curTags  = show.tags
```

So instead of just passing `curShow` to a component I now have to pass `curShow` and `curTags`, even though tags is a property of shows.  In this example this is a small problem but in my real code I have a number of situations like this with deep data and the length of the data section and `props` array is getting really long.

I'm going through my code and fixing these warnings and my small neat code is getting bloated.  Is there a better way of doing this?
