### ISSUE TITLE
$watch multiple keys?

### ISSUE THREAD

**Issue by BigBlueHat** [vuejs/Discussion#40]
I'm likely Doing It Wrong, but I have several instances where I need changes to have happened to multiple variables prior to triggering a method. Currently, I check for the proper values (or any value) of the variables inside the triggered method, but that means my code still looks like:

```
this.$watch('user', function() {
  this.fetchData()
})
this.$watch('project', function() {
  this.fetchData()
});
```

What I'd hoped to do was:

```
this.$watch(['user', 'project'], function() {
  this.fetchData();
});
```

Perhaps I'm just being lazy, but that looks prettier anyway. :grinning:

**Comment by aristidesfl** [comment]
I have a related problem. I'm converting a Rivets app which uses an adapter to beautifully integrate with chrome.storage.

I was trying to achieve the same with Vue, and hoping there was a way to watch an object, and get the callback anytime there was a change in a property of the object.
```
  window.vm = new Vue
    el: '.options'
    data:
      options:  # by default
        'flavour': 'banana'
        'color': 'yellow'
        'size': 3
        'shape': 'square'
        'amount': 40
    created: ->
      chrome.storage.local.get @options, (results) =>
        @options = results
    watch:
      options: (changedProperties) -> chrome.storage.local.set(changedProperties)
```

However the watch callback only get's executed if the object itself is replaced like with `@options = results`. The callback never gets executed when a property changes as a result a binding like `v-model="options.flavour"`. 

Ideally one of the arguments in the watch callback should receive an object with the changes. So if for example the flavour had changed to "chocolate", changedProperties would contain the following object: `{flavour: chocolate"}`
